"""Rules for DILI assay screening."""

from __future__ import annotations


DILI_RULES = {
    "direct_human_dili": {
        "tier": "Tier 1",
        "base_score": 125,
        "keywords": [
            "drug induced liver injury",
            "drug-induced liver injury",
            "dili",
            "hepatotoxicity",
            "hepatotoxic",
            "liver injury",
            "hepatic injury",
            "liver toxicity",
            "hepatic toxicity",
            "hepatic adverse event",
            "liver adverse event",
            "drug induced hepatitis",
            "drug-induced hepatitis",
            "toxic hepatitis",
            "acute liver failure",
            "fulminant hepatic failure",
            "liver failure",
            "liver transplant",
            "fatal liver injury",
            "liver related death",
            "liver-related death",
            "withdrawal due to hepatotoxicity",
            "withdrawn due to hepatotoxicity",
            "boxed warning for liver",
            "black box warning for liver",
            "hy's law",
            "hys law",
            "hy law",
            "jaundice",
            "transaminase elevation",
            "liver enzyme elevation",
            "alanine aminotransferase",
            "aspartate aminotransferase",
            "bilirubin elevation",
            "alkaline phosphatase elevation",
            "cholestatic hepatitis",
            "hepatocellular injury",
            "cholestatic injury",
            "mixed liver injury",
        ],
        "endpoints": [
            "dili",
            "hepatotoxicity",
            "liver injury",
            "liver toxicity",
            "alt",
            "ast",
            "alanine aminotransferase",
            "aspartate aminotransferase",
            "bilirubin",
            "total bilirubin",
            "alkaline phosphatase",
            "alp",
            "ggt",
            "jaundice",
            "hy's law",
            "hys law",
            "hy law",
        ],
    },
    "in_vivo_liver_injury": {
        "tier": "Tier 2",
        "base_score": 105,
        "keywords": [
            "liver histopathology",
            "hepatic histopathology",
            "liver pathology",
            "hepatic pathology",
            "hepatic necrosis",
            "liver necrosis",
            "centrilobular necrosis",
            "hepatocellular necrosis",
            "hepatocellular degeneration",
            "hepatocyte degeneration",
            "liver inflammation",
            "hepatic inflammation",
            "portal inflammation",
            "bile duct injury",
            "bile duct hyperplasia",
            "liver fibrosis",
            "hepatic fibrosis",
            "liver weight",
            "serum alt",
            "serum ast",
            "serum bilirubin",
            "serum bile acid",
            "plasma bile acid",
            "in vivo hepatotoxicity",
            "in vivo liver toxicity",
            "repeated dose liver toxicity",
            "repeat dose liver toxicity",
            "subacute liver toxicity",
            "subchronic liver toxicity",
            "chronic liver toxicity",
            "noael with liver",
            "loael with liver",
            "mtd with liver",
            "toxicokinetic exposure margin",
        ],
        "endpoints": [
            "histopathology",
            "necrosis",
            "degeneration",
            "inflammation",
            "liver weight",
            "alt",
            "ast",
            "alp",
            "bilirubin",
            "ggt",
            "bile acid",
            "noael",
            "loael",
            "mtd",
            "liver toxic dose",
        ],
    },
    "cholestasis_transporter": {
        "tier": "Tier 3",
        "base_score": 95,
        "keywords": [
            "bsep",
            "bile salt export pump",
            "abcb11",
            "bile acid efflux",
            "bile acid transport",
            "bile salt transport",
            "taurocholate efflux",
            "taurocholate transport",
            "canalicular bile acid",
            "mrp2",
            "abcc2",
            "mrp3",
            "abcc3",
            "mrp4",
            "abcc4",
            "mdr3",
            "abcb4",
            "ntcp",
            "slc10a1",
            "oatp1b1",
            "slco1b1",
            "oatp1b3",
            "slco1b3",
            "hepatobiliary transporter",
            "cholestasis",
            "cholestatic",
            "bile acid accumulation",
            "impaired bile flow",
            "bile canalicular network",
        ],
        "endpoints": [
            "inhibition",
            "ic50",
            "transport",
            "efflux",
            "uptake",
            "substrate",
            "bile acid",
            "taurocholate",
            "cholestasis",
        ],
    },
    "mitochondrial_organelle_stress": {
        "tier": "Tier 4",
        "base_score": 90,
        "keywords": [
            "mitochondrial toxicity",
            "mitochondrial dysfunction",
            "mitochondrial membrane potential",
            "mmp loss",
            "oxygen consumption rate",
            "ocr",
            "respiratory chain",
            "electron transport chain",
            "complex i inhibition",
            "complex ii inhibition",
            "complex iii inhibition",
            "complex iv inhibition",
            "mitochondrial respiration",
            "mitochondrial swelling",
            "atp depletion",
            "cellular atp",
            "oxidative stress",
            "reactive oxygen species",
            "ros",
            "glutathione depletion",
            "gsh depletion",
            "nrf2",
            "nfe2l2",
            "antioxidant response",
            "jnk activation",
            "er stress",
            "endoplasmic reticulum stress",
            "unfolded protein response",
            "upr",
            "phospholipidosis",
            "lysosomal trapping",
            "lysosomal stress",
            "steatosis",
            "lipid accumulation",
        ],
        "endpoints": [
            "mitochondrial membrane potential",
            "oxygen consumption",
            "ocr",
            "atp",
            "ros",
            "glutathione",
            "gsh",
            "nrf2",
            "oxidative stress",
            "phospholipidosis",
            "steatosis",
        ],
    },
    "reactive_metabolite_immune": {
        "tier": "Tier 5",
        "base_score": 90,
        "keywords": [
            "reactive metabolite",
            "bioactivation",
            "covalent binding",
            "protein adduct",
            "drug protein adduct",
            "drug-protein adduct",
            "gsh adduct",
            "glutathione adduct",
            "cysteine trapping",
            "cyanide trapping",
            "quinone imine",
            "quinoneimine",
            "quinone methide",
            "acyl glucuronide",
            "iminium ion",
            "metabolic activation",
            "metabolite mediated toxicity",
            "metabolite-mediated toxicity",
            "cyp mediated bioactivation",
            "cyp-mediated bioactivation",
            "idiosyncratic dili",
            "idiosyncratic liver injury",
            "immune mediated liver injury",
            "immune-mediated liver injury",
            "hla association",
            "t cell response",
            "cytokine release with liver injury",
            "inflammasome",
            "danger signal",
        ],
        "endpoints": [
            "adduct",
            "covalent binding",
            "bioactivation",
            "reactive metabolite",
            "glutathione",
            "gsh",
            "metabolite",
            "hla",
            "t cell",
            "cytokine",
        ],
    },
    "hepatic_cell_exposure_context": {
        "tier": "Tier 6",
        "base_score": 70,
        "keywords": [
            "primary human hepatocyte",
            "primary hepatocyte",
            "human hepatocyte",
            "rat hepatocyte",
            "hepatocyte viability",
            "hepatocyte cytotoxicity",
            "heparg",
            "hepg2",
            "liver spheroid",
            "hepatic spheroid",
            "liver organoid",
            "hepatic organoid",
            "micropatterned hepatocyte",
            "ldh release",
            "apoptosis",
            "necrosis",
            "caspase activation",
            "high content hepatotoxicity",
            "high-content hepatotoxicity",
            "toxicogenomics",
            "transcriptomic dili",
            "liver stress gene expression",
            "liver toxicity signature",
            "metabolomics liver toxicity",
            "proteomics liver toxicity",
            "high daily dose",
            "high lipophilicity",
            "rule of two",
            "cationic amphiphilicity",
            "liver accumulation",
            "hepatic extraction",
            "extensive hepatic metabolism",
        ],
        "endpoints": [
            "cell viability",
            "viability",
            "cytotoxicity",
            "cc50",
            "ic50",
            "ldh",
            "apoptosis",
            "necrosis",
            "caspase",
            "gene expression",
            "signature",
        ],
    },
}


HEPATOBILIARY_TARGET_GENES = {
    "ABCB11",
    "ABCC2",
    "ABCC3",
    "ABCC4",
    "ABCB4",
    "SLC10A1",
    "SLCO1B1",
    "SLCO1B3",
}


HEPATIC_METABOLISM_TARGET_GENES = {
    "CYP3A4",
    "CYP2C9",
    "CYP2C19",
    "CYP2D6",
    "CYP1A2",
    "UGT1A1",
    "NR1I2",
    "NR1I3",
    "NR1H4",
    "NFE2L2",
}


STRONG_DILI_TERMS = [
    "drug induced liver injury",
    "drug-induced liver injury",
    "dili",
    "hepatotoxicity",
    "hepatotoxic",
    "liver injury",
    "acute liver failure",
    "fulminant hepatic failure",
    "hy's law",
    "hys law",
    "hy law",
    "jaundice",
    "cholestasis",
    "cholestatic",
    "bsep",
    "bile salt export pump",
    "abcb11",
    "mitochondrial toxicity",
    "reactive metabolite",
    "bioactivation",
    "gsh adduct",
    "glutathione adduct",
    "primary hepatocyte",
    "heparg",
]


LIVER_CONTEXT_TERMS = [
    "liver",
    "hepatic",
    "hepatotoxic",
    "hepatotoxicity",
    "hepatocyte",
    "hepatocytes",
    "hepatocellular",
    "hepatobiliary",
    "heparg",
    "hepg2",
    "cholestasis",
    "cholestatic",
    "bile acid",
    "bile salt",
]


HUMAN_OR_CLINICAL_TERMS = [
    "human",
    "patient",
    "volunteer",
    "clinical",
    "clinical trial",
    "postmarketing",
    "post market",
    "post-market",
    "label",
    "boxed warning",
    "black box warning",
    "fda",
    "ltkb",
    "dilirank",
]


IN_VIVO_TERMS = [
    "in vivo",
    "rat",
    "rats",
    "mouse",
    "mice",
    "dog",
    "dogs",
    "monkey",
    "non human primate",
    "non-human primate",
    "rabbit",
    "hamster",
    "guinea pig",
    "animal",
    "oral dose",
    "intravenous dose",
    "repeated dose",
    "repeat dose",
    "subacute",
    "subchronic",
    "chronic",
]


LIVER_CANCER_EFFICACY_NOISE = [
    "hepatocellular carcinoma",
    "hepatoma",
    "liver cancer",
    "hcc",
    "anti proliferative",
    "antiproliferative",
    "growth inhibition",
    "tumor growth",
    "tumour growth",
    "anticancer",
    "anti cancer",
    "anti-cancer",
]


NON_DILI_SAFETY_NOISE = [
    "herg",
    "kcn h2",
    "kcnh2",
    "qt prolongation",
    "qtc",
    "cardiotoxicity",
    "nephrotoxicity",
    "renal toxicity",
    "kidney toxicity",
    "neurotoxicity",
    "skin sensitization",
    "skin sensitisation",
    "phototoxicity",
    "ames",
    "micronucleus",
    "genotoxicity",
    "mutagenicity",
]


EFFICACY_NOISE = [
    "antiviral",
    "anti viral",
    "anti-viral",
    "antiinfective",
    "anti infective",
    "anti-infective",
    "antibacterial",
    "antimicrobial",
    "replication inhibition",
    "cytopathic effect",
    "cpe inhibition",
    "parasite growth",
    "plasmodium",
    "trypanosoma",
    "leishmania",
]


GENERIC_TARGET_NOISE = [
    "receptor binding",
    "target binding",
    "binding affinity",
    "enzyme inhibition",
    "kinase inhibition",
    "kinase assay",
    "biochemical assay",
    "enzyme activity",
    "functional activity",
    "inhibitor potency",
    "agonist",
    "antagonist",
]


GENERIC_CYP_INHIBITION_TERMS = [
    "cyp inhibition",
    "cyp3a4 inhibition",
    "cyp2c9 inhibition",
    "cyp2c19 inhibition",
    "cyp2d6 inhibition",
    "cyp1a2 inhibition",
    "time dependent inhibition",
    "mechanism based inhibition",
    "ic50",
]


WEAK_TERMS = [
    "activity",
    "inhibition",
    "ic50",
    "ec50",
    "ki",
    "kd",
    "cc50",
    "gi50",
    "viability",
    "cytotoxicity",
    "stress",
    "gene expression",
]
