"""Rules for Skin_Reaction assay screening."""

from __future__ import annotations


SKIN_REACTION_RULES = {
    "direct_skin_reaction": {
        "tier": "Tier 1",
        "base_score": 120,
        "keywords": [
            "skin reaction",
            "skin adverse reaction",
            "dermatologic adverse event",
            "dermatological adverse event",
            "adverse skin",
            "skin rash",
            "rash",
            "erythema",
            "edema",
            "oedema",
            "pruritus",
            "itching",
            "urticaria",
            "contact dermatitis",
            "allergic contact dermatitis",
            "contact allergy",
            "skin allergy",
            "dermal allergy",
            "human patch test",
            "patch test",
            "human maximization test",
            "human maximisation test",
            "repeated insult patch test",
            "hript",
            "ript",
            "local lymph node assay",
            "llna",
            "brdu elisa",
            "brdu fcm",
            "stimulation index",
            "ec3",
            "guinea pig maximization",
            "guinea pig maximisation",
            "gpmt",
            "buehler",
            "skin sensitization",
            "skin sensitisation",
            "dermal sensitization",
            "dermal sensitisation",
            "dermal irritation",
            "skin irritation",
            "dermal toxicity",
            "skin toxicity",
            "draize skin",
        ],
        "endpoints": [
            "sensitization",
            "sensitisation",
            "skin sensitization",
            "skin sensitisation",
            "irritation",
            "dermal irritation",
            "stimulation index",
            "si",
            "ec3",
            "erythema",
            "edema",
            "oedema",
            "rash",
            "pruritus",
            "non sensitizer",
            "non-sensitizer",
            "non irritant",
            "non-irritant",
        ],
    },
    "sensitization_aop_key_event": {
        "tier": "Tier 2",
        "base_score": 100,
        "keywords": [
            "dpra",
            "adra",
            "kdpra",
            "direct peptide reactivity",
            "peptide reactivity",
            "peptide depletion",
            "cysteine depletion",
            "lysine depletion",
            "amino acid derivative reactivity",
            "hapten",
            "haptenation",
            "protein binding",
            "covalent binding",
            "keratinosens",
            "lusens",
            "episensa",
            "are nrf2",
            "are-nrf2",
            "antioxidant response element",
            "nrf2",
            "keap1",
            "keratinocyte activation",
            "h clat",
            "h-clat",
            "u sens",
            "u-sens",
            "il 8 luc",
            "il-8 luc",
            "gardskin",
            "dendritic cell activation",
            "thp 1 activation",
            "u937 activation",
            "cd54",
            "cd86",
            "il 8 reporter",
            "glutathione depletion",
            "gsh reactivity",
            "thiol reactivity",
            "cysteine adduct",
        ],
        "endpoints": [
            "depletion",
            "cysteine depletion",
            "lysine depletion",
            "peptide depletion",
            "activation",
            "luciferase induction",
            "fold induction",
            "ec1.5",
            "ec 1.5",
            "cd54",
            "cd86",
            "il-8",
            "il 8",
            "glutathione",
            "gsh",
        ],
    },
    "phototoxicity_or_photosafety": {
        "tier": "Tier 3",
        "base_score": 95,
        "keywords": [
            "phototoxicity",
            "photo toxicity",
            "photoallergy",
            "photo allergy",
            "photoirritation",
            "photo irritation",
            "photosafety",
            "3t3 nru",
            "neutral red uptake phototoxicity",
            "photo irritation factor",
            "photoirritation factor",
            "pif",
            "mean photo effect",
            "mpe",
            "uva",
            "uvb",
            "photocytotoxicity",
            "rhe phototoxicity",
            "reconstructed human epidermis phototoxicity",
        ],
        "endpoints": [
            "phototoxicity",
            "photoirritation factor",
            "pif",
            "mean photo effect",
            "mpe",
            "ic50",
            "cell viability",
            "viability",
        ],
    },
    "irritation_corrosion_local_damage": {
        "tier": "Tier 3",
        "base_score": 90,
        "keywords": [
            "reconstructed human epidermis",
            "rhe",
            "episkin",
            "epiderm",
            "skinethic",
            "skin irritation",
            "skin corrosion",
            "dermal irritation",
            "dermal corrosion",
            "mtt skin",
            "tissue viability",
            "keratinocyte viability",
            "hacat viability",
            "epidermal cell cytotoxicity",
            "dermal fibroblast cytotoxicity",
            "ldh release",
            "skin cell cytotoxicity",
            "skin inflammation",
            "barrier disruption",
            "il 1 alpha",
            "il-1 alpha",
            "il 6",
            "il-6",
            "il 8",
            "il-8",
            "tnf alpha",
            "tnf-alpha",
            "pge2",
            "cox 2",
            "oxidative stress in skin",
        ],
        "endpoints": [
            "viability",
            "cell viability",
            "tissue viability",
            "cytotoxicity",
            "irritation",
            "corrosion",
            "ldh release",
            "il-1 alpha",
            "il-6",
            "il-8",
            "tnf",
            "pge2",
        ],
    },
    "skin_exposure_modifier": {
        "tier": "Tier 4",
        "base_score": 75,
        "keywords": [
            "skin absorption",
            "dermal absorption",
            "percutaneous absorption",
            "skin permeation",
            "skin permeability",
            "dermal permeability",
            "transdermal permeation",
            "transdermal delivery",
            "franz diffusion",
            "diffusion cell",
            "skin flux",
            "flux through skin",
            "permeability coefficient",
            "logkp",
            "log kp",
            "kp",
            "jmax",
            "skin retention",
            "epidermis retention",
            "dermis retention",
            "stratum corneum",
            "tape stripping",
            "skin deposition",
            "skin pampa",
            "artificial membrane skin",
        ],
        "endpoints": [
            "permeability",
            "permeation",
            "absorption",
            "flux",
            "kp",
            "logkp",
            "log kp",
            "jmax",
            "retention",
            "skin deposition",
        ],
    },
    "weak_skin_context": {
        "tier": "Tier 5",
        "base_score": 45,
        "keywords": [
            "cytotoxicity",
            "cell viability",
            "cell survival",
            "cell death",
            "apoptosis",
            "necrosis",
            "cell proliferation",
            "immune activation",
            "cytokine",
            "inflammation",
            "nf-kb",
            "nfkb",
            "cox",
            "lox",
            "dermatology",
            "skin",
            "keratinocyte",
            "fibroblast",
            "hacat",
        ],
        "endpoints": [
            "cc50",
            "gi50",
            "ic50",
            "ec50",
            "viability",
            "cytotoxicity",
            "activity",
            "inhibition",
        ],
    },
}


STRONG_SKIN_REACTION_TERMS = [
    "skin sensitization",
    "skin sensitisation",
    "contact dermatitis",
    "contact allergy",
    "patch test",
    "hript",
    "local lymph node",
    "llna",
    "ec3",
    "stimulation index",
    "gpmt",
    "buehler",
    "dpra",
    "adra",
    "keratinosens",
    "h-clat",
    "u-sens",
    "il-8 luc",
    "gardskin",
    "phototoxicity",
    "photoirritation",
    "skin irritation",
    "skin corrosion",
    "dermal irritation",
    "dermal toxicity",
]


DERMATOLOGY_EFFICACY_NOISE = [
    "anti acne",
    "anti-acne",
    "acne treatment",
    "anti psoriasis",
    "anti-psoriasis",
    "psoriasis treatment",
    "atopic dermatitis treatment",
    "eczema treatment",
    "wound healing",
    "skin whitening",
    "melanogenesis",
    "tyrosinase inhibition",
    "melanoma",
    "anti aging",
    "anti-aging",
    "wrinkle",
    "collagenase",
    "elastase",
    "hair growth",
    "alopecia",
    "sebocyte",
    "antimicrobial",
    "antifungal",
    "antiviral",
    "anti inflammatory",
    "anti-inflammatory",
    "antiinflammatory",
    "protection against",
    "protective activity",
    "protective effect",
    "reduction in",
    "lipoxygenase inhibition",
    "lox inhibition",
    "cyclooxygenase inhibition",
    "permeation enhancer",
    "penetration enhancer",
    "potentiation of",
    "enhancement of transdermal permeation",
    "enhancement of skin permeation",
]


TARGET_POTENCY_NOISE = [
    "receptor binding",
    "target binding",
    "binding affinity",
    "enzyme inhibition",
    "kinase inhibition",
    "kinase assay",
    "biochemical assay",
    "high throughput biochemical",
    "tr-fret",
    "time-resolved fluorescence resonance energy transfer",
    "enzyme activity",
    "enzyme assay",
    "enzymatic assay",
    "kinase activity",
    "residual kinase activity",
    "inhibitor potency",
    "mean inhibition",
    "activity inhibition",
    "autophosphorylation",
    "alphascreen",
    "omnia assay",
    "nanosyn",
    "potency assessment",
    "tbd tbd",
    "fret measurement",
    "fret measurements",
    "bovine skin gelatin",
    "functional activity",
    "inhibition of",
    "inhibitor of",
    "antagonist",
    "agonist",
    "inhibitor activity",
]


WEAK_TERMS = [
    "activity",
    "inhibition",
    "ic50",
    "ec50",
    "ki",
    "kd",
    "cc50",
    "gi50",
    "viability",
    "cytotoxicity",
    "inflammation",
    "cytokine",
]
