"""Rules for Bioavailability_Ma assay screening."""

from __future__ import annotations


BIOAVAILABILITY_RULES = {
    "direct_absolute_bioavailability": {
        "tier": "Tier 1",
        "base_score": 110,
        "keywords": [
            "absolute oral bioavailability",
            "oral bioavailability",
            "bioavailability",
            "fraction bioavailable",
            "fraction of dose bioavailable",
            "oral iv ratio",
            "oral/iv ratio",
            "oral to iv",
            "po iv ratio",
        ],
        "endpoints": [
            "bioavailability",
            "absolute bioavailability",
            "oral bioavailability",
            "%f",
            "f%",
            "f",
            "fraction bioavailable",
            "auc oral iv ratio",
            "oral iv auc ratio",
        ],
    },
    "in_vivo_oral_exposure_absorption": {
        "tier": "Tier 2",
        "base_score": 90,
        "keywords": [
            "oral exposure",
            "oral administration",
            "oral dose",
            "po dose",
            "by oral route",
            "plasma exposure",
            "systemic exposure",
            "human intestinal absorption",
            "intestinal absorption",
            "fraction absorbed",
            "percent absorbed",
            "oral absorption",
            "effective permeability",
            "intestinal permeability",
            "jejunal permeability",
            "intestinal perfusion",
            "single pass intestinal perfusion",
            "in situ intestinal perfusion",
            "portal absorption",
        ],
        "endpoints": [
            "auc",
            "auc0 t",
            "auc0 inf",
            "aucinf",
            "cmax",
            "tmax",
            "plasma concentration",
            "fraction absorbed",
            "percent absorbed",
            "fa",
            "fabs",
            "hia",
            "peff",
            "effective permeability",
            "intestinal permeability",
        ],
    },
    "in_vitro_permeability_efflux": {
        "tier": "Tier 3",
        "base_score": 75,
        "keywords": [
            "caco 2",
            "caco2",
            "mdck",
            "mdck mdr1",
            "mdckii",
            "pampa",
            "parallel artificial membrane",
            "apparent permeability",
            "papp",
            "apical to basolateral",
            "basolateral to apical",
            "bidirectional",
            "efflux ratio",
            "intestinal efflux",
            "p gp substrate",
            "p glycoprotein substrate",
            "pgp substrate",
            "abcb1 substrate",
            "mdr1 substrate",
            "bcrp substrate",
            "abcg2 substrate",
            "mrp substrate",
            "transporter mediated efflux",
        ],
        "endpoints": [
            "papp",
            "logpapp",
            "apparent permeability",
            "permeability",
            "permeability coefficient",
            "efflux ratio",
            "substrate",
            "transport",
            "drug transport",
            "uptake",
        ],
    },
    "solubility_dissolution_gi_stability": {
        "tier": "Tier 4",
        "base_score": 70,
        "keywords": [
            "aqueous solubility",
            "kinetic solubility",
            "thermodynamic solubility",
            "intrinsic solubility",
            "solubility",
            "dissolution",
            "percent dissolved",
            "gastric stability",
            "intestinal stability",
            "simulated gastric fluid",
            "simulated intestinal fluid",
            "gi stability",
        ],
        "endpoints": [
            "solubility",
            "aqueous solubility",
            "kinetic solubility",
            "thermodynamic solubility",
            "logs",
            "log s",
            "dissolution",
            "dissolution rate",
            "percent dissolved",
            "stability",
            "half life",
            "t1/2",
        ],
    },
    "metabolism_first_pass_clearance": {
        "tier": "Tier 5",
        "base_score": 80,
        "keywords": [
            "microsomal stability",
            "liver microsome stability",
            "human liver microsome",
            "rat liver microsome",
            "hepatocyte stability",
            "liver s9",
            "s9 stability",
            "metabolic stability",
            "metabolic turnover",
            "substrate depletion",
            "intrinsic clearance",
            "hepatic clearance",
            "first pass metabolism",
            "first-pass metabolism",
            "hepatic extraction",
            "cyp substrate",
            "cyp metabolism",
        ],
        "endpoints": [
            "intrinsic clearance",
            "clint",
            "clearance",
            "hepatic clearance",
            "cl",
            "percent remaining",
            "remaining",
            "half life",
            "t1/2",
            "metabolic stability",
            "turnover",
        ],
    },
    "formulation_food_relative_bioavailability": {
        "tier": "Tier 6",
        "base_score": 45,
        "keywords": [
            "relative bioavailability",
            "food effect",
            "fed fasted",
            "fed/fasted",
            "high fat meal",
            "fasting",
            "formulation bioavailability",
            "formulation comparison",
            "tablet",
            "capsule",
            "solution",
            "suspension",
            "salt form",
            "solid dispersion",
            "nanoparticle formulation",
        ],
        "endpoints": [
            "relative bioavailability",
            "auc ratio",
            "cmax ratio",
            "exposure ratio",
            "ratio",
        ],
    },
}

EFFLUX_TARGET_GENES = {
    "ABCB1",
    "ABCG2",
    "ABCC1",
    "ABCC2",
    "ABCC4",
    "ABCC5",
}

EFFLUX_TARGET_PHRASES = [
    "p glycoprotein",
    "p-glycoprotein",
    "atp dependent translocase abcb1",
    "breast cancer resistance protein",
    "broad substrate specificity atp binding cassette transporter abcg2",
    "multidrug resistance associated protein",
]

CYP_TARGET_GENES = {
    "CYP1A2",
    "CYP2C8",
    "CYP2C9",
    "CYP2C19",
    "CYP2D6",
    "CYP3A4",
    "CYP3A5",
}

TRANSPORTER_TARGETS = EFFLUX_TARGET_GENES

WEAK_TERMS = {
    "activity",
    "ratio",
    "inhibition",
    "ic50",
    "ki",
    "ec50",
    "kd",
    "binding",
    "substrate",
    "transport",
    "uptake",
    "stability",
    "half life",
    "clearance",
    "auc",
    "cmax",
}

NEGATIVE_KEYWORDS = [
    "cytotoxicity",
    "cell viability",
    "proliferation",
    "antiproliferative",
    "antitumor",
    "anti tumor",
    "xenograft",
    "tumor growth",
    "cancer cell line",
    "receptor binding",
    "target binding",
    "binding affinity",
    "enzyme inhibition",
    "kinase inhibition",
    "functional activity",
    "mic",
    "antimicrobial activity",
]

NON_ORAL_ROUTE_TERMS = [
    "intravenous",
    " i v ",
    " iv ",
    "intraperitoneal",
    " i p ",
    " ip ",
    "subcutaneous",
    " s c ",
    " sc ",
    "topical",
    "dermal",
    "ocular",
    "intranasal",
    "inhaled",
]

ORAL_ROUTE_TERMS = [
    "oral",
    "po",
    "p o",
    "by mouth",
    "gavage",
    "intragastric",
]
