"""Generate committed compiled-prompt examples for every reasoning stage.

Renders the exact system+user prompt for each stage of the bioavailability_ma
pipeline -- single-molecule, group branches (all three formats), and final synthesis
-- from one frozen real datapoint, and writes them to ``prompt_examples/``. These are
compiled prompts only (no model output, no hidden labels/scores beyond what a format
intentionally shows).

A golden-file test (`test_prompt_examples.py`) re-renders from the same fixture and
diffs the committed files, so the examples cannot drift from the prompt code: after
any prompt change, re-run ``python -m ...dump_prompt_examples --write``.

Usage:
  python -m tools.chembl_tool.tasks.bioavailability_ma.prompt_audit.dump_prompt_examples          # check (diff, exit 1 on drift)
  python -m tools.chembl_tool.tasks.bioavailability_ma.prompt_audit.dump_prompt_examples --write  # regenerate committed files
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from tools.chembl_tool.tasks.bioavailability_ma.group_prompt_render import build_group_messages
from tools.chembl_tool.tasks.bioavailability_ma.run_reasoning_pipeline import (
    final_messages,
    legacy_group_messages,
    single_molecule_messages,
)

_REPO_ROOT = Path(__file__).resolve().parents[5]
_FIXTURE_DIR = _REPO_ROOT / "tests/chembl_tool/tasks/bioavailability_ma/fixtures/prompt_examples"
FIXTURE_PATH = _FIXTURE_DIR / "fixture.json"
EXAMPLES_DIR = Path(__file__).with_name("prompt_examples")


def _format(name: str, messages: list[dict[str, str]]) -> str:
    system = next(m["content"] for m in messages if m["role"] == "system")
    user = next(m["content"] for m in messages if m["role"] == "user")
    return (
        f"# Compiled prompt example: {name}\n"
        "# Source: fixtures/prompt_examples/fixture.json (real datapoint, query index 0, group Fg)\n"
        "# Generated by dump_prompt_examples.py -- do not edit by hand.\n"
        "\n===== SYSTEM =====\n"
        f"{system}\n"
        "\n===== USER =====\n"
        f"{user}\n"
    )


def render_examples(fixture: dict) -> dict[str, str]:
    """Return {filename: compiled-prompt-text} for every stage/format."""
    query = fixture["query"]
    group = fixture["group"]
    coverage = fixture["coverage"]
    retrieval = {"query": query, "coverage": coverage}
    min_sim = coverage.get("min_similarity", 0.0)
    return {
        "single.prompt.txt": _format("single-molecule", single_molecule_messages(query)),
        "group.legacy.prompt.txt": _format(
            "group / legacy", legacy_group_messages(query, group)
        ),
        "group.morganfingerprint.prompt.txt": _format(
            "group / morganfingerprint",
            build_group_messages(query, group, prompt_format="morganfingerprint",
                                 options={"prompt_min_similarity": min_sim}),
        ),
        "group.morganfingerprint.full.prompt.txt": _format(
            "group / morganfingerprint / presentation-style=full",
            build_group_messages(query, group, prompt_format="morganfingerprint",
                                 options={"prompt_min_similarity": min_sim,
                                          "presentation_style": "full"}),
        ),
        "group.assay_transfer_tool.prompt.txt": _format(
            "group / assay_transfer_tool",
            build_group_messages(
                query,
                group,
                prompt_format="assay_transfer_tool",
                options={"group_tools_enabled": False},
            ),
        ),
        "group.assay_transfer_tool.assay-transfer.prompt.txt": _format(
            "group / assay_transfer_tool / assay-transfer output schema",
            build_group_messages(
                query,
                group,
                prompt_format="assay_transfer_tool",
                options={
                    "group_tools_enabled": False,
                    "output_schema_profile": "assay-transfer",
                },
            ),
        ),
        "group.assay_transfer_tool.full.prompt.txt": _format(
            "group / assay_transfer_tool / presentation-style=full",
            build_group_messages(query, group, prompt_format="assay_transfer_tool",
                                 options={"presentation_style": "full"}),
        ),
        "final.prompt.txt": _format(
            "final synthesis",
            final_messages(retrieval, fixture["single_output"], fixture["group_outputs"]),
        ),
    }


def load_fixture() -> dict:
    return json.loads(FIXTURE_PATH.read_text(encoding="utf-8"))


def _readme() -> str:
    return (
        "# Compiled prompt examples\n\n"
        "One example of the exact prompt sent to GLM at each pipeline stage, compiled\n"
        "from a single frozen real datapoint (query index 0, group Fg). These are\n"
        "**compiled prompts only** -- no model output. The group stage has one example\n"
        "per format (legacy, morganfingerprint, assay_transfer_tool), plus the\n"
        "evidence-centric assay-transfer output profile. The two text formats also\n"
        "have a `.full.` variant showing `--presentation-style full` (per-source fields).\n\n"
        "Do not edit by hand. Regenerate after any prompt-code change:\n\n"
        "    python -m tools.chembl_tool.tasks.bioavailability_ma.prompt_audit.dump_prompt_examples --write\n\n"
        "A golden-file test (tests/.../test_prompt_examples.py) fails if these drift.\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="Write files (default: check and report drift).")
    args = parser.parse_args(argv)

    examples = render_examples(load_fixture())
    EXAMPLES_DIR.mkdir(parents=True, exist_ok=True)
    stale: list[str] = []
    for name, text in examples.items():
        path = EXAMPLES_DIR / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(name)
        if args.write:
            path.write_text(text, encoding="utf-8")
    if args.write:
        (EXAMPLES_DIR / "README.md").write_text(_readme(), encoding="utf-8")

    if args.write:
        print(f"wrote {len(examples)} examples to {EXAMPLES_DIR}" + (f" (updated: {stale})" if stale else " (no changes)"))
        return 0
    if stale:
        print(f"STALE prompt examples: {stale}\nRun: python -m tools.chembl_tool.tasks.bioavailability_ma.prompt_audit.dump_prompt_examples --write", file=sys.stderr)
        return 1
    print("prompt examples up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
