"""Rules for BBB Martins assay screening."""

from __future__ import annotations


BBB_RULES = {
    "direct_bbb": {
        "tier": "Tier 1",
        "base_score": 100,
        "keywords": [
            "blood brain barrier",
            "bbb permeability",
            "brain penetration",
            "brain uptake",
            "brain exposure",
            "brain plasma",
            "brain to plasma",
            "brain blood",
            "brain to blood",
            "brain concentration",
            "brain level",
            "brain auc",
            "logbb",
            "kp uu brain",
            "kpuu brain",
            "k p uu brain",
            "unbound brain",
            "unbound plasma",
            "fraction unbound brain",
            "fu brain",
            "brain binding",
            "in situ brain perfusion",
            "brain perfusion",
            "brain uptake index",
            "brain penetration index",
            "bui",
            "bpi",
            "permeability surface area",
            "ps product",
            "csf plasma",
            "csf to plasma",
            "cerebrospinal fluid plasma",
        ],
        "endpoints": [
            "logbb",
            "k p uu brain",
            "kp uu brain",
            "kpuu brain",
            "brain plasma",
            "brain plasma ratio",
            "brain to plasma ratio",
            "brain blood",
            "brain to blood ratio",
            "brain uptake",
            "brain uptake index",
            "brain penetration index",
            "brain concentration",
            "brain level",
            "csf plasma",
            "csf to plasma ratio",
            "ps product",
        ],
    },
    "passive_permeability": {
        "tier": "Tier 2",
        "base_score": 70,
        "keywords": [
            "pampa bbb",
            "bbb pampa",
            "parallel artificial membrane",
            "mdck mdr1",
            "mdr1 mdck",
            "mdckii mdr1",
            "mdck2 mdr1",
            "mdck",
            "mdckii",
            "mdck2",
            "caco 2",
            "caco2",
            "hcmec d3",
            "bend 3",
            "bmec",
            "bbmec",
            "rbec",
            "brain endothelial",
            "brain microvessel endothelial",
            "transwell",
            "apical to basolateral",
            "basolateral to apical",
            "papp",
            "logpapp",
            "apparent permeability",
            "permeability coefficient",
        ],
        "endpoints": [
            "papp",
            "logpapp",
            "apparent permeability",
            "permeability coefficient",
            "caco 2 papp",
            "caco 2 permeability",
            "efflux ratio",
        ],
    },
    "efflux": {
        "tier": "Tier 3",
        "base_score": 85,
        "keywords": [
            "p gp",
            "p glycoprotein",
            "pglycoprotein",
            "mdr1",
            "abcb1",
            "bcrp",
            "abcg2",
            "breast cancer resistance protein",
            "mrp1",
            "mrp2",
            "mrp4",
            "mrp5",
            "abcc1",
            "abcc2",
            "abcc4",
            "abcc5",
            "efflux",
            "efflux ratio",
            "substrate",
            "bidirectional",
            "basolateral to apical",
            "apical to basolateral",
            "rhodamine 123",
            "calcein am",
            "digoxin",
            "prazosin",
            "vinblastine",
            "tariquidar",
            "elacridar",
            "verapamil",
            "cyclosporin a",
            "ko143",
            "atpase",
        ],
        "endpoints": [
            "efflux ratio",
            "substrate",
            "transport",
            "papp",
            "atpase",
            "ic50",
            "ki",
        ],
    },
    "influx": {
        "tier": "Tier 4",
        "base_score": 55,
        "keywords": [
            "lat1",
            "slc7a5",
            "glut1",
            "slc2a1",
            "oatp1a2",
            "slco1a2",
            "oat3",
            "slc22a8",
            "mct1",
            "slc16a1",
            "transferrin receptor",
            "tfrc",
            "influx",
            "uptake",
            "transport",
        ],
        "endpoints": [
            "uptake",
            "transport",
            "substrate",
        ],
    },
}

EFFLUX_TARGET_GENES = {
    "ABCB1",
    "ABCG2",
    "ABCC1",
    "ABCC2",
    "ABCC4",
    "ABCC5",
}

INFLUX_TARGET_GENES = {
    "SLC7A5",
    "SLC2A1",
    "SLCO1A2",
    "SLC22A8",
    "SLC16A1",
    "TFRC",
}

TRANSPORTER_TARGETS = EFFLUX_TARGET_GENES | INFLUX_TARGET_GENES

EFFLUX_TARGET_PHRASES = [
    "atp dependent translocase abcb1",
    "multidrug resistance protein 1",
    "p glycoprotein",
    "breast cancer resistance protein",
    "broad substrate specificity atp binding cassette transporter abcg2",
    "atp binding cassette sub family c member 1",
    "atp binding cassette sub family c member 2",
    "atp binding cassette sub family c member 4",
    "atp binding cassette sub family c member 5",
    "multidrug resistance associated protein 1",
    "multidrug resistance associated protein 2",
    "multidrug resistance associated protein 4",
    "multidrug resistance associated protein 5",
]

INFLUX_TARGET_PHRASES = [
    "large neutral amino acids transporter small subunit 1",
    "solute carrier family 7 member 5",
    "facilitated glucose transporter member 1",
    "solute carrier family 2",
    "solute carrier organic anion transporter family member 1a2",
    "organic anion transporter 3",
    "monocarboxylate transporter 1",
    "transferrin receptor",
]

WEAK_TERMS = {
    "kp",
    "ps",
    "kin",
    "csf",
    "pampa",
    "permeability",
    "pe",
    "a b",
    "b a",
    "transport",
    "uptake",
    "substrate",
    "ic50",
    "ki",
}

NEGATIVE_KEYWORDS = [
    "cytotoxicity",
    "cell viability",
    "proliferation",
    "tumor",
    "cancer cell line",
    "dopamine receptor",
    "serotonin receptor",
    "gaba receptor",
    "muscarinic receptor",
    "histamine receptor",
    "opioid receptor",
    "cannabinoid receptor",
    "kinase inhibition",
    "thymidine uptake",
    "glucose uptake",
    "oxygen uptake",
    "tumor uptake",
]
